---
#"Description" : "Ansible Playbook to Configure a Secondary HDD & Apache

- name: Configure Secondary HDD & Configure Docker 
  hosts: localhost
  gather_facts: False
  become: true
  remote_user: ubuntu

  roles:
    - common
#    - docker
#    - rancher
#    - k8s
#    - helm
#    - oom


  

