---
- name: Add k8s repo key
  become: true
  apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  register_errors: add_k8s_key
  ignore_errors: true


- name: Add k8s repo key
  become: true
  apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      update_cache: yes
      state: present

- name: Install k8s
  become: true
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
      - kubelet
      - kubeadm
      - kubectl

- name: Reset kubernetes cluster
  become: true
  shell: kubeadm reset

- name: Create k8s master node
  become: true
  become_user: root
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: init_cluster

- name: Create k8s config directory
  file: path="~/.kube" state=directory

- name: Change permissions of .kube/config
  become: yes
  file: path=/etc/kubernetes/admin.conf mode=0775

- name: Copy admin.confg to Home directory
  when: init_cluster
  copy:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config
      mode: 0755
      remote_src: True

- name: Enable and restart kubelet engine
  become: yes
  systemd:
      name: kubelet
      daemon_reload: yes
      state: restarted
      enabled: yes
  register: started_kubelet

- name: Install weave networking
  shell: |
      export kubever=$(kubectl version | base64 | tr -d '\n')
      kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"

- name: Untaint ndoes
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/master-
